# Generated by Django 3.2.7 on 2022-04-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkdin', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('collegename', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=50)),
                ('passingyear', models.CharField(max_length=6)),
                ('skills', models.CharField(max_length=1000)),
                ('experience', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('isCreated', models.DateTimeField(auto_now_add=True)),
                ('isUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companylogo', models.ImageField(upload_to='jobapp/img/company')),
                ('jobname', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=100)),
                ('jobdesc', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('companyemail', models.EmailField(max_length=254)),
                ('salary', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('requirments', models.TextField()),
                ('lastdate', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Jobapplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('experience', models.CharField(max_length=10)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.candidate')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.candidate_resume')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('companyname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster')),
            ],
        ),
        migrations.AddField(
            model_name='candidate_resume',
            name='resumeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster'),
        ),
    ]
