# Generated by Django 3.2.7 on 2022-04-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('isCreated', models.DateTimeField(auto_now_add=True)),
                ('isUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=100)),
                ('jobdesc', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('companyemail', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('requirments', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('companyname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='jobapp/img/company')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('profilePic', models.ImageField(upload_to='jobapp/img/candidate')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.usermaster')),
            ],
        ),
    ]
